import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";

const jetbrainsMono = localFont({
	src: "./fonts/JetBrainsMono.ttf",
	variable: "--font-code",
	weight: "100 900",
});

const manrope = localFont({
	src: "./fonts/Manrope.ttf",
	variable: "--font-text",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body className={`${jetbrainsMono.variable} ${manrope.variable}`}>
		{children}
		</body>
		</html>
	);
}
